---
- name: Ensure dependencies are installed
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - conntrack
    state: present
    update_cache: yes

- name: Download Minikube binary
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
    force: yes

- name: Get latest stable Kubernetes version
  shell: "curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt"
  register: kubectl_version
  changed_when: false

- name: Download kubectl binary
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
    force: yes

- name: Ensure user is added to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Start Minikube as normal user
  become: false
  shell: |
    minikube start --driver=docker
  args:
    creates: /home/{{ ansible_user_id }}/.minikube

- name: Notify user to re-login for docker group to apply
  debug:
    msg: "Please log out and log back in for Docker group membership to take effect."
